from io import BytesIO

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)


def create_report(
    review,
    label,
    confidence,
    processing_time,
):

    buffer = BytesIO()

    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "Title",
        parent=styles["Title"],
        fontSize=24,
        textColor=colors.HexColor("#2563EB"),
        spaceAfter=20,
    )

    heading_style = ParagraphStyle(
        "Heading",
        parent=styles["Heading2"],
        fontSize=15,
        textColor=colors.HexColor("#111827"),
        spaceBefore=15,
        spaceAfter=10,
    )

    body_style = ParagraphStyle(
        "Body",
        parent=styles["BodyText"],
        fontSize=10,
        leading=16,
    )

    story = []

    story.append(
        Paragraph(
            "TrustLens AI",
            title_style,
        )
    )

    story.append(
        Paragraph(
            "Fake Review Detection Report",
            heading_style,
        )
    )

    story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            "Review",
            heading_style,
        )
    )

    safe_review = (
        review
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )

    story.append(
        Paragraph(
            safe_review,
            body_style,
        )
    )

    story.append(Spacer(1, 20))

    data = [
        ["Prediction", label],
        ["Confidence", f"{confidence}%"],
        ["Model", "Linear SVM"],
        ["Vectorization", "TF-IDF"],
        [
            "Processing Time",
            f"{processing_time:.3f} seconds",
        ],
    ]

    table = Table(
        data,
        colWidths=[150, 300],
    )

    table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (0, -1),
                    colors.HexColor("#EFF6FF"),
                ),
                (
                    "TEXTCOLOR",
                    (0, 0),
                    (-1, -1),
                    colors.HexColor("#111827"),
                ),
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.HexColor("#CBD5E1"),
                ),
                (
                    "PADDING",
                    (0, 0),
                    (-1, -1),
                    10,
                ),
            ]
        )
    )

    story.append(table)

    story.append(Spacer(1, 30))

    story.append(
        Paragraph(
            "Generated by TrustLens AI",
            body_style,
        )
    )

    document.build(story)

    return buffer.getvalue()